# ===============================
# DATABASE CONFIG
# ===============================
# The ${VAR:default} syntax allows it to use the cloud DB when deployed on Render,
# but safely falls back to your local MySQL when testing on your laptop!
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/campus_portal}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9090

spring.web.resources.static-locations=file:uploads/
# ===============================
# GMAIL SMTP (FOR OTP SENDING)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.username=${MAIL_USERNAME:asmithag113@gmail.com}
spring.mail.password=${MAIL_PASSWORD:grfuapjvlwyyvjxn}

mailboxlayer.api.key=${MAILBOX_API_KEY:74739706c7856dffddbb4aa1abf916a8}