# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=mysql://avnadmin:AVNS_IbkIc6lYlu86KuU9vAf@mysql-ae9e65e-asmitha1902-60e9.l.aivencloud.com:10633/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_IbkIc6lYlu86KuU9vAf

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9090

spring.web.resources.static-locations=file:uploads/
# ===============================
# GMAIL SMTP (FOR OTP SENDING)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=asmithag113@gmail.com
spring.mail.password=grfuapjvlwyyvjxn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

mailboxlayer.api.key=74739706c7856dffddbb4aa1abf916a8
